[[redirects]]
  from = "https://fatigueindex.netlify.app"
  to = "https://fatigueindex.ga"
  status = 301
  force = true

[[redirects]]
  from = "https://fatigueindex.netlify.app/*"
  to = "https://fatigueindex.ga"
  status = 301
  force = true